### PR TITLE
Remove query-runner from the deployment

### PR DESCRIPTION
**Pull request by camdencheek**
This removes query-runner from the docker deployment. Depends on https://github.com/sourcegraph/sourcegraph/pull/28333

### Checklist

* [x] Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/4030
* [x] All images have a valid tag and SHA256 sum

### CODE REVIEW

**Comment by slimsag** [comment]
You need to remove this too: https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml#L294-L313

**Review by slimsag — APPROVED** [review]

**Review by slimsag — CHANGES_REQUESTED** [review]
Actually, there's more you need to remove: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/deploy-sourcegraph-docker%24+query-runner&patternType=literal

**Comment by camdencheek** [comment]
Aah shoot. Thanks for catching those. I'll take another look at this with fresh eyes in the morning. Converting this to draft in the mean time.

**Review by bobheadxi — CHANGES_REQUESTED** [review]
> Sister deploy-sourcegraph change

The PR you linked here is for `deploy-sourcegraph-dot-com`, not `deploy-sourcegraph` https://github.com/sourcegraph/deploy-sourcegraph

**Comment by camdencheek** [comment]
@bobheadxi @slimsag After a fresh coat of sleep, I've updated this PR to remove the remaining references to query-runner. I've also fixed the link in the description to a sister PR on `deploy-sourcegraph` and fixed the smoke tests to expect one less container. 

Sorry about the incomplete first pass!

**Comment by camdencheek** [comment]
@bobheadxi @slimsag After a fresh coat of sleep, I've updated this PR to remove the remaining references to query-runner. I've also fixed the link in the description to a sister PR on `deploy-sourcegraph` and fixed the smoke tests to expect one less container. 

Sorry about the incomplete first pass!

**Review by slimsag — APPROVED** [review]

**Review by bobheadxi — APPROVED** [review]
Thank you!

**Pull request merged**
