### PR TITLE
release: sourcegraph@3.39.1

### PR DESCRIPTION
**Pull request by coury-clark**
This pull request is part of the Sourcegraph 3.39.1 release.

* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34545)

### :warning: Additional changes required

These steps must be completed before this PR can be merged, unless otherwise stated. Push any required changes directly to this PR branch.

- [x] Follow the [release guide](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md) to complete this PR (note: `pure-docker` release is optional for patch releases)

cc @coury-clark

### Test plan

CI checks in this repository should pass, and a manual review should confirm if the generated changes are correct.

### CODE REVIEW

**Review by camdencheek — APPROVED** [review]

**Comment by coury-clark** [comment]
Deferring pure-docker updates until tomorrow until we can unfreeze the 3.39.1-customer-replica branch

**Comment by camdencheek** [comment]
In the issue template, it does mention that "pure-docker release is optional for patch releases". I _think_ we can just merge this?

**Comment by coury-clark** [comment]
I saw that, but my assumption was that optional = missing the patch. Maybe I'm wrong about that.

**Comment by camdencheek** [comment]
Yeah, I think you're right. My guess is it's just not a contract requirement for this customer.

**Pull request merged**
