### PR TITLE
caddy: bump up caddy to 2.7.3

### PR DESCRIPTION
**Pull request by evict**
This commit bumps up Caddy and mitigates all the high and critically reported findings.

### Checklist

* [ ] Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change:
* [ ] Sister [customer-replica](https://github.com/sourcegraph/deploy-sourcegraph-docker-customer-replica-1) change (if necessary, for any changes affecting pure-docker or configuration):
* [x] All images have a valid tag and SHA256 sum
### Test plan
Caddy runs locally, proxies the requests successfully to frontend.

### CODE REVIEW

**Comment by willdollman** [comment]
https://github.com/caddyserver/caddy/releases

> The ask endpoint is now required to enable On-Demand TLS (https://github.com/caddyserver/caddy/commit/b97c76fb4789b8da0b80f5a2c1c1c5bebba163b5) for catch-all or wildcard hosts.

**Comment by burmudar** [comment]
The mono repo is still on 2.4.5?

**Comment by evict** [comment]
> The mono repo is still on 2.4.5?

Correct. We wanna make sure the change @willdollman mentioned above won't break SSL. Do you have an idea about that?

**Comment by burmudar** [comment]
> > The mono repo is still on 2.4.5?
> 
> Correct. We want to make sure the change @willdollman mentioned above won't break SSL. Do you have an idea about that?

No idea tbh. I would need to investigate

**Comment by evict** [comment]
Waiting for the docker image for version 2.7.3.

**Comment by burmudar** [comment]
> Waiting for the docker image for version 2.7.3.

Should be availbable once https://github.com/docker-library/official-images/pull/15189 is merged!

**Review by burmudar — APPROVED** [review]

**Pull request merged**
